version: '3'
 
services:
    nginx_web_1:
        container_name: haproxy_nginx_con1
        build: ./nginx/web1
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: 192.168.0.10
                aliases: 
                    - nginx1
    nginx_web_2:
        container_name: haproxy_nginx_con2
        build: ./nginx/web2
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: 192.168.0.20
                aliases: 
                    - nginx2
    haproxy:
        build: ./haproxy
        ports:
            - 80:80
        expose:
            - 80
        networks:
            public_net:
                ipv4_address: 192.168.0.2
        environment:
            - NGINX_1_IP=192.168.0.10
            - NGINX_2_IP=192.168.0.20
            - NGINX_EXPOSED_PORT=80
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "192.168.0.0/24"
                  gateway: "192.168.0.1"